<a href="https://colab.research.google.com/github/sharath507/minerva_task/blob/main/minerva_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:

# Generating synthetic data for demonstration
# Replace with your dataset
np.random.seed(42)
X = np.random.randint(40, 100, size=(1000, 6))  # Past 6 years' scores
y = np.random.randint(40, 100, size=(1000, 1))

In [ ]:
print( X[:10])
print(y[:10])

[[78 91 68 54 82 47]
 [60 78 97 58 62 50]
 [50 63 92 75 79 63]
 [42 61 92 41 63 83]
 [69 77 41 99 60 72]
 [51 97 61 83 64 88]
 [66 98 81 67 99 55]
 [54 86 90 83 94 91]
 [96 42 76 90 46 60]
 [48 78 57 43 64 99]]
[[88]
 [60]
 [48]
 [45]
 [90]
 [84]
 [74]
 [78]
 [61]
 [80]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
print(X_test[:10])
print(y_test[:10])

[[52 80 62 58 84 50]
 [69 45 68 47 83 84]
 [92 74 80 98 53 69]
 [77 88 40 64 90 75]
 [54 90 52 58 88 45]
 [62 83 78 54 95 88]
 [41 74 57 53 59 57]
 [95 88 52 77 88 85]
 [83 41 63 73 66 94]
 [64 78 88 99 67 72]]
[[71]
 [71]
 [60]
 [67]
 [67]
 [78]
 [93]
 [64]
 [57]
 [94]]


In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
print(X_test[:10])
print(y_test[:10])

[[52 80 62 58 84 50]
 [69 45 68 47 83 84]
 [92 74 80 98 53 69]
 [77 88 40 64 90 75]
 [54 90 52 58 88 45]
 [62 83 78 54 95 88]
 [41 74 57 53 59 57]
 [95 88 52 77 88 85]
 [83 41 63 73 66 94]
 [64 78 88 99 67 72]]
[[71]
 [71]
 [60]
 [67]
 [67]
 [78]
 [93]
 [64]
 [57]
 [94]]


In [ ]:
model = Sequential([
    Dense(64, input_dim=6, activation='relu'),  # Hidden layer 1
    Dense(32, activation='relu'),               # Hidden layer 2
    Dense(1)                                    # Output layer (single value for marks)
])


In [ ]:
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# Training the model
history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test), verbose=1)


Epoch 1/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 600.3050 - mae: 20.3559 - val_loss: 421.8697 - val_mae: 17.4017
Epoch 2/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 373.8133 - mae: 16.0124 - val_loss: 376.3673 - val_mae: 16.6684
Epoch 3/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 334.9514 - mae: 15.0875 - val_loss: 371.3827 - val_mae: 16.5717
Epoch 4/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 344.2609 - mae: 15.6109 - val_loss: 380.6636 - val_mae: 16.7792
Epoch 5/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 335.6980 - mae: 15.4353 - val_loss: 388.5323 - val_mae: 16.9027
Epoch 6/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 340.7214 - mae: 15.4516 - val_loss: 369.5733 - val_mae: 16.5314
Epoch 7/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 350.0898 - mae: 15.5227 - val_loss: 378.5421 - val_mae: 16.8016
Epoch 8/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 347.2990 - mae: 15.6970 - val_loss: 394.6076 - val_mae: 17.0386
Epoch 9/50
25/25 ━━━━━━━

In [ ]:
loss, mae = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Loss: {loss:.4f}, Test MAE: {mae:.4f}")

# Predicting future scores
y_pred = model.predict(X_test[:5])
print("Predicted scores:", y_pred.flatten())
print("Actual scores:", y_test[:5].flatten())


Test Loss: 378.6741, Test MAE: 16.7167
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
Predicted scores: [63.615536 62.846718 75.289246 76.15615  66.32548 ]
Actual scores: [71 71 60 67 67]


In [ ]:
# prompt: give the code to display the variable x&y

print("X:", X)
print("y:", y)

X: [[78 91 68 54 82 47]
 [60 78 97 58 62 50]
 [50 63 92 75 79 63]
 ...
 [63 64 84 94 85 71]
 [94 71 44 75 85 81]
 [88 81 97 78 55 72]]
y: [[88]
 [60]
 [48]
 [45]
 [90]
 [84]
 [74]
 [78]
 [61]
 [80]
 [93]
 [44]
 [81]
 [62]
 [56]
 [51]
 [62]
 [55]
 [42]
 [69]
 [96]
 [61]
 [48]
 [68]
 [86]
 [76]
 [62]
 [52]
 [71]
 [85]
 [91]
 [86]
 [87]
 [62]
 [84]
 [56]
 [94]
 [79]
 [60]
 [41]
 [76]
 [45]
 [83]
 [57]
 [69]
 [61]
 [93]
 [72]
 [69]
 [56]
 [82]
 [71]
 [81]
 [90]
 [53]
 [97]
 [49]
 [86]
 [99]
 [90]
 [75]
 [73]
 [48]
 [81]
 [67]
 [50]
 [53]
 [78]
 [94]
 [86]
 [93]
 [58]
 [93]
 [54]
 [67]
 [63]
 [47]
 [82]
 [48]
 [86]
 [72]
 [72]
 [58]
 [42]
 [49]
 [79]
 [86]
 [81]
 [40]
 [68]
 [89]
 [73]
 [90]
 [52]
 [93]
 [40]
 [73]
 [68]
 [87]
 [86]
 [52]
 [87]
 [88]
 [92]
 [68]
 [78]
 [63]
 [65]
 [56]
 [46]
 [52]
 [44]
 [65]
 [88]
 [42]
 [46]
 [97]
 [88]
 [78]
 [92]
 [40]
 [88]
 [56]
 [82]
 [64]
 [98]
 [42]
 [54]
 [68]
 [92]
 [82]
 [71]
 [65]
 [99]
 [55]
 [64]
 [93]
 [67]
 [48]
 [95]
 [95]
 [40]
 [68]
 [96

In [ ]:
# prompt: give the code to concate the x and y varible into the table format

import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# ... (Your existing code) ...

# Concatenate X and y into a DataFrame
combined_data = np.concatenate((X, y), axis=1)
df = pd.DataFrame(combined_data)

# Add column names (adjust as needed)
column_names = [f'X_{i}' for i in range(X.shape[1])] + ['y']
df.columns = column_names

print(df.head()) #prints the first 5 rows
print(df) # prints the entire dataframe

   X_0  X_1  X_2  X_3  X_4  X_5   y
0   78   91   68   54   82   47  88
1   60   78   97   58   62   50  60
2   50   63   92   75   79   63  48
3   42   61   92   41   63   83  45
4   69   77   41   99   60   72  90
     X_0  X_1  X_2  X_3  X_4  X_5   y
0     78   91   68   54   82   47  88
1     60   78   97   58   62   50  60
2     50   63   92   75   79   63  48
3     42   61   92   41   63   83  45
4     69   77   41   99   60   72  90
..   ...  ...  ...  ...  ...  ...  ..
995   40   43   51   99   66   95  59
996   81   62   64   60   97   91  79
997   63   64   84   94   85   71  49
998   94   71   44   75   85   81  58
999   88   81   97   78   55   72  42

[1000 rows x 7 columns]


In [ ]:
y = model.predict(X_test[0])
print(y)

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)
  • training=False
  • mask=None

In [ ]:
print(X_train[0])
print(X[0])

[0.44067797 0.13559322 0.23728814 0.23728814 0.42372881 0.69491525]
[78 91 68 54 82 47]


In [ ]:
# print(var[0])
print(X_test[0])

[0.77966102 0.81355932 0.69491525 0.62711864 0.28813559 0.74576271]


In [ ]:
import pandas as pd
import numpy as np

# Parameters
num_students = 1000  # Increase the number of students for better model training
num_exams = 10

# Creating a synthetic dataset
np.random.seed(42)
data = {
    'student_id': range(num_students),
    'exam_1': np.random.randint(50, 100, num_students),
    'exam_2': np.random.randint(50, 100, num_students),
    'exam_3': np.random.randint(50, 100, num_students),
    'exam_4': np.random.randint(50, 100, num_students),
    'exam_5': np.random.randint(50, 100, num_students),
    'exam_6': np.random.randint(50, 100, num_students),
    'exam_7': np.random.randint(50, 100, num_students),
    'exam_8': np.random.randint(50, 100, num_students),
    'exam_9': np.random.randint(50, 100, num_students),
    'exam_10': np.random.randint(50, 100, num_students),
}

# Creating DataFrame
df = pd.DataFrame(data)

# Optional: Adding attendance and participation
df['attendance'] = np.random.uniform(0.7, 1.0, num_students)  # Attendance as a percentage
df['participation'] = np.random.randint(0, 2, num_students)  # 0 or 1 for participation

# Save the dataset
df.to_csv('student_marks.csv', index=False)

In [ ]:
print(df)

     student_id  exam_1  exam_2  exam_3  exam_4  exam_5  exam_6  exam_7  \
0             0      88      82      52      56      68      94      80   
1             1      78      71      55      53      74      66      52   
2             2      64      70      58      78      71      89      57   
3             3      92      55      55      63      80      70      73   
4             4      57      55      58      52      66      51      64   
..          ...     ...     ...     ...     ...     ...     ...     ...   
995         995      75      91      95      90      81      75      52   
996         996      83      93      53      79      95      77      84   
997         997      94      98      94      62      96      81      82   
998         998      55      89      69      70      97      94      73   
999         999      86      60      66      68      72      51      68   

     exam_8  exam_9  exam_10  attendance  participation  
0        67      94       58    0.964491 

In [ ]:
print("Predicted scores:", y_pred.flatten())
print("Actual scores:", y_test[:5].flatten())

NameError: name 'y_pred' is not defined

In [ ]:
import numpy as np

# Example: 100 students, 6 timesteps (years), 1 feature (marks per year)
# X = np.random.rand(100, 6, 6)
X = np.random.randint(40, 100, size=(100, 6,6))  # Input
y = np.random.randint(40,100,size=(100,6))     # Output (future marks)


In [ ]:
print(X[0],y[0])

[[98 92 78 50 53 62]
 [92 55 89 60 94 94]
 [43 72 93 86 53 58]
 [98 44 75 70 84 57]
 [83 70 94 69 60 86]
 [69 94 80 43 44 80]] [90 77 51 63 52 79]


In [ ]:
# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler()
# X_scaled = X.reshape(-1, 1)  # Reshape to 2D for scaling
# X_scaled = scaler.fit_transform(X_scaled).reshape(X.shape)  # Reshape back to 3D


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Define the model
model = Sequential([
    LSTM(64, activation='relu', input_shape=(6, 6)),  # 6 timesteps, 6 feature
    Dense(6)  # six output (future marks)
])

# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Train the model
history = model.fit(X_train, y_train, epochs=50, batch_size=16, validation_data=(X_test, y_test), verbose=1)

# Evaluate the model
loss, mae = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss:.4f}, Test MAE: {mae:.4f}")


Epoch 1/50


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 99ms/step - loss: 4890.2041 - mae: 65.8690 - val_loss: 4578.0640 - val_mae: 63.9796
Epoch 2/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 4102.8589 - mae: 59.9141 - val_loss: 3869.3198 - val_mae: 57.7947
Epoch 3/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 3294.8474 - mae: 52.8064 - val_loss: 2561.4282 - val_mae: 43.0901
Epoch 4/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1885.5845 - mae: 37.3078 - val_loss: 1257.2177 - val_mae: 29.2729
Epoch 5/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1091.4451 - mae: 27.0711 - val_loss: 1121.4812 - val_mae: 25.9020
Epoch 6/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 807.0751 - mae: 22.7954 - val_loss: 824.3786 - val_mae: 22.1002
Epoch 7/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 556.4999 - mae: 19.2899 - val_loss: 540.5805 - val_mae: 18.7730
Epoch 8/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 478.9567 - mae: 17.7177 - val_loss: 461.4776 - val_mae: 17.2632
Epoch 9/50
5/5 ━━━━━━━━━━━━━━━━━━

In [ ]:
# prompt: give the code to predict the value of the given input array

# Example input array (replace with your actual input)
input_array = np.array([[60, 70, 80, 90, 85, 75]])

# Preprocess the input array using the same scaler used during training
input_array_scaled = scaler.transform(input_array)

# Make the prediction
predicted_value = model.predict(input_array_scaled)

print("Predicted value:", predicted_value)

In [ ]:
print(X_train[0])

[[57 46 95 59 77 50]
 [83 97 55 90 94 66]
 [90 50 55 62 99 98]
 [51 98 79 42 41 99]
 [77 87 91 63 68 86]
 [85 73 59 57 53 57]]


In [ ]:
model.predict(X_train[0].reshape(1,6,6) )

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step


array([[58.42833 , 55.28693 , 71.32301 , 89.68169 , 47.858467, 94.181244]],
      dtype=float32)

In [ ]:
print(X_train[0].reshape(1,6,6) )

[[[57 46 95 59 77 50]
  [83 97 55 90 94 66]
  [90 50 55 62 99 98]
  [51 98 79 42 41 99]
  [77 87 91 63 68 86]
  [85 73 59 57 53 57]]]


In [ ]:
# prompt: give the code to export the model to joblib

import joblib

# Assuming 'model' is your trained Keras model
joblib.dump(model, 'my_model.joblib')

['my_model.joblib']

In [ ]:
# prompt: give the code to import the joblib model and to predict the output from the given array

import joblib
import numpy as np

# Load the saved model
loaded_model = joblib.load('my_model.joblib')

# Example input array (replace with your actual input)
input_array = np.array([[[60, 70, 80, 90, 85, 75]]])

# Assuming the input shape is (1, 6, 6) for LSTM model
# Reshape the input if necessary
# input_array = input_array.reshape(1, 6, 6)

# Make the prediction
predicted_value = loaded_model.predict(X_train[0].reshape(1,6,6))

print("Predicted value:", predicted_value)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step
Predicted value: [[58.42833  55.28693  71.32301  89.68169  47.858467 94.181244]]
